openapi: 3.0.0
info:
  title: Books API
  version: 0.0.0
  description: A simple Express Books API
servers:
  - url: http://localhost:5001
tags:
  - name: Books
    description: The books managing API
paths:
  /api/books:
    get:
      summary: Get all books
      tags: [Books]
      responses:
        '200':
          description: A list of books
    post:
      summary: Create a new book
      tags: [Books]
      parameters:
        - name: authorization
          in: header
          required: true
          description: Bearer token for authorization
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                author:
                  type: string
                price:
                  type: string
                stock:
                  type: number
                category_id:
                  type: number
      responses:
        '201':
          description: Book created
  /api/books/{id}:
    get:
      summary: get book by id
      tags: [Books]
      parameters:
        - name: id
          in: path
          required: true
          description: Book id fetch 
          schema: 
           type: number
      responses:
        '200':
          description: Book fetched successfully
    put:
      summary: update a book
      tags: [Books]
      parameters:
        - name: authorization
          in: header
          required: true
          description: Bearer token for authorization
          schema:
            type: string
        - name: id
          in: path
          required: true
          description: Book id to update
          schema: 
           type: number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                author:
                  type: string
                price:
                  type: string
                stock:
                  type: number
                category_id:
                  type: number
      responses:
        '200':
          description: Book updated
    delete:
      summary: delete a book
      tags: [Books]
      parameters:
        - name: authorization
          in: header
          required: true
          description: Bearer token for authorization
          schema:
            type: string
        - name: id
          in: path
          required: true
          description: Book id to delete
          schema: 
           type: number
      responses:
        '204':
          description: Book Deleted

